In [2]:
import numpy as np

In [3]:
#np.__version__
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [4]:
#Arraycriado apartir de uma lista, podem ser, int, float, boolean, operações de numeros complexos e etc...
array= np.array([1,2,3,4,5,6,7,8,9])
print(array)

[1 2 3 4 5 6 7 8 9]


In [5]:
#func soma acumulada
array.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [6]:
array.shape

(9,)

In [7]:
array_dois = np.arange(0,10,1)
print(array_dois)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
array_dois.shape

(10,)

In [9]:
array_tres = np.arange(0,10,0.25)
print(array_tres)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75
 7.   7.25 7.5  7.75 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


In [10]:
#vai ser util nem Machine learn e deep learn
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
#Cria uma matriz principal
array_quatro = np.eye(10)
print(array_quatro)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [12]:
#Cria uma matriz principal recebedo um array de entrada
array_cinco = np.diag(np.array([1,2,3,4]))
print(array_cinco)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [13]:
print(np.linspace(0,10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [14]:
print(np.linspace(0,10,15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [16]:
print(np.logspace(0,5,10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


matriz_um = np.array([1,2,3],[4,5,6],[7,8,9])
print(matriz_um)

In [18]:
#Matriz 3 por 3
matriz_um = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz_um)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(matriz_um.shape)

(3, 3)


In [20]:
lista_aux = [[10,58,57],[25,34,69],[80,42,21]]

In [22]:
matriz_dois = np.matrix(lista_aux)
print(matriz_dois)

[[10 58 57]
 [25 34 69]
 [80 42 21]]


In [24]:
print(matriz_dois.size)

9


In [26]:
print(matriz_dois.itemsize, "\n")

4 



In [32]:
#np pega o tipo da entrada, mas np decida o tipo que vai ser
#mas é possivivel alterrar o tipo para um desejado, -> dtype = np.float64 ou -> dtype = np.int32
w = np.array([1,2])
x = np.array([1.0,2.0])
y = np.array([1.0,2.0], dtype = np.int32)
z = np.array([1,2], dtype = np.float64)
print(w.dtype, x.dtype, y.dtype, z.dtype)

int32 float64 int32 float64
